# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfef695fb1f31a28f256f2f3de0853ecc234b7f9dc63eae7b75a7e216458d3f9d52ee47f1e75267d1a3429aa4093660fd63f24b410a216db6aa24023200a7b5b

test:
  secret_key_base: 96e95e3629dbb8d0342ae67818de2b93cea59f02cb32f92e2f3dfa94493c19d16c3411c887457a4e418a438a23573df6c2e055e692ca50e9830a6b5915b0bc98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
